( load "table-get-put.scm" )
( load "scheme-number-package.scm" )
( load "rational-package.scm" )
( load "generic-rec-polar.scm" )
( load "complex-package.scm" )
( load "generic-op.scm" )

( install-rectangular-package )
( install-polar-package )
( install-complex-package )
( install-scheme-number-package )
( install-rational-package )

( define x ( make-complex-from-real-imag 4 3 ) )
( define y ( make-scheme-number 5 ) )
( define z ( make-rational 4 7 ) )
( define x2 ( make-complex-from-real-imag 4 6 ) )
( define z2 ( make-rational 3 7 ) )
( define main ( magnitude-1 x ) )
