( load "queue.scm" )
( load "wire.scm" )
( load "module.scm" )
( load "simulate.scm" )
( load "agenda.scm" )

( define the-agenda ( make-agenda ) )
( define inverter-delay 2 )
( define and-gate-delay 3 )
( define or-gate-delay 5 )

( define input-1 ( make-wire ) )
( define input-2 ( make-wire ) )
( define sum ( make-wire ) )
( define carry ( make-wire ) )
